apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wayshub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ryuzu98/wayshub-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: wayshub
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
